### ISSUE TITLE
How do I sign up?

### ISSUE THREAD

**Issue by sylveon** [Microsoft/Hacktoberfest#1]
Is this like the DO Hacktoberfest where we have to fill a form with our GitHub username to participate, or will any contributor to Microsoft repos receive a message at the end of month asking for shipping details? Or is it perhaps something else?

**Comment by jotasprout** [comment]
@sylveon Keep an eye on [https://hacktoberfest.digitalocean.com/](https://hacktoberfest.digitalocean.com/) and sign up for alerts. You sign up for Hacktoberfest there as the first step.

**Comment by sylveon** [comment]
Yes, I will sign up there, I already subscribed for alerts. What I'm wondering is about Microsoft's Hacktoberfest event.

**Comment by berndverst** [comment]
> Is this like the DO Hacktoberfest where we have to fill a form with our GitHub username to participate, or will any contributor to Microsoft repos receive a message at the end of month asking for shipping details? Or is it perhaps something else?

@sylveon we will post a form later this week. But you can complete the form anytime until the end of October and then we'll consider any PRs made during October. All you will submit is your GitHub username and email address. Once Hacktoberfest ends we will email you a link and unique coupon code to order your shirt!

Follow @OpenAtMicrosoft on Twitter or check our [Microsoft Open blog](open.microsoft.com) at the end of this week.

Please note that this is completely separate from the Digital Ocean Hacktoberfest signup. You can of course participate in their Hacktoberfest challenge, but to be eligible for our Microsoft challenge you'll need to complete a different form.

**Comment by sylveon** [comment]
Awesome, that's all I needed to know. Thank you very much 😃
