### ISSUE TITLE
Steps

### ISSUE THREAD

**Issue by thecodingaviator** [Microsoft/Hacktoberfest#5]
Hey,
Had a couple of questions-

1. Does our pull request have to be accepted?
2. After open a PR, what's the next step? :)

**Comment by jotasprout** [comment]
I don't know if Microsoft will have different rules but, FWIW, official Hacktoberfest rules are that you must submit the pull requests -- they do not need to be accepted.

**Comment by thecodingaviator** [comment]
Yeah, I've been wanting to clarify that, I'm familiar with Hacktoberfest rules, not sure about the Microsoft section though

**Comment by crweiner** [comment]
See my PR for the official rules on how to participate in Microsoft's own t-shirt giveaway. Hopefully they'll include it in this repository so it's easier to see.
PR: #9 

From the announcement:

> If you make at least one pull request* on any Microsoft repo between October 1st – 31st, you’ll receive a limited edition t-shirt designed by Ashley McNamara 

> _* Yes, really! Any pull request. Please keep in mind the spirit of open source, meaningfully improve projects or documentation, and be kind to the project maintainers and your fellow contributors and community members_.

[https://open.microsoft.com/2018/09/30/join-hacktoberfest-2018-celebration-microsoft/](https://open.microsoft.com/2018/09/30/join-hacktoberfest-2018-celebration-microsoft/)

**Comment by thecodingaviator** [comment]
Thanks @crweiner !

**Comment by crweiner** [comment]
@thecodingaviator No problem!
Just to make things crystal clear, after you submit the PR you need to fill out their form here:
https://aka.ms/hacktoberfestshirt
They will email a special code and ordering instructions sometime at a later date. See #9 and the link I posted yesterday for the full details.
